name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        release: [V00-00-00-RC2, stable, trunk]
        platform: [ubuntu-18.04, macOS-10.14]

    steps:
    - uses: actions/checkout@v1
    - name: "Checkout and build icecube-combo framework"
      run: bash -v -e ./install.sh
      env:
        BUILD_STEP: ICECUBE_SIMULATION_BUILD
        RELEASE: ${{ matrix.release }}
        PLATFORM: ${{ matrix.platform }}
        SVN: ${{ secrets.SVN }}
        SVN_ICECUBE_USERNAME: icecube
        SVN_ICECUBE_PASSWORD: ${{ secrets.SVN_ICECUBE_PASSWORD }}
    - name: Build icecube-combo with monopole-generator
      run: bash -v -e ./install.sh
      env:
        BUILD_STEP: MONOPOLE_GENERATOR_BUILD
        SVN: ${{ secrets.SVN }}
        SVN_ICECUBE_USERNAME: icecube
        SVN_ICECUBE_PASSWORD: ${{ secrets.SVN_ICECUBE_PASSWORD }}
        RELEASE: ${{ matrix.release }}
    - name: Build test binaries
      run: bash -v -e ./install.sh
      env:
        BUILD_STEP: BUILD_TEST_BINS
        RELEASE: ${{ matrix.release }}
    - name: Run monopole-generator python tests
      run: bash -v -e ./install.sh
      env:
        BUILD_STEP: MONOPOLE_GENERATOR_PYTHON_TESTS
        RELEASE: ${{ matrix.release }}
    - name: Run monopole-generator cpp tests
      run: bash -v -e ./install.sh
      env:
        BUILD_STEP: MONOPOLE_GENERATOR_TESTS
        RELEASE: ${{ matrix.release }}
