name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [macOS-10.14]

    steps:
    - uses: actions/checkout@v1
    - name: Install required system packages
      run: bash -v -e ./install-on-mac-os.sh
      env:
        BUILD_STEP: SYSTEM_PACKAGES
    - name: Build icecube-simulation framework
      run: bash -v -e ./install-on-mac-os.sh
      env:
        BUILD_STEP: ICECUBE_SIMULATION_BUILD
        SVN: ${{ secrets.SVN }}
        SVN_ICECUBE_USERNAME: icecube
        SVN_ICECUBE_PASSWORD: ${{ secrets.SVN_ICECUBE_PASSWORD }}
    - name: Build icecube-simulation with monopole-generator
      run: bash -v -e ./install-on-mac-os.sh
      env:
        BUILD_STEP: MONOPOLE_GENERATOR_BUILD
        SVN: ${{ secrets.SVN }}
        SVN_ICECUBE_USERNAME: icecube
        SVN_ICECUBE_PASSWORD: ${{ secrets.SVN_ICECUBE_PASSWORD }}
    - name: Build test binaries
      run: bash -v -e ./install-on-mac-os.sh
      env:
        BUILD_STEP: BUILD_TEST_BINS
    - name: Run monopole-generator tests
      run: bash -v -e ./install-on-mac-os.sh
      env:
        BUILD_STEP: MONOPOLE_GENERATOR_TESTS
